# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
target 'TrackerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  
  pod 'IQKeyboardManagerSwift'
  pod 'ActionSheetPicker-3.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/DynamicLinks'
  pod 'SnapKit'
  pod 'CRRefresh'
  pod 'R.swift'
  pod 'SwifterSwift/UIKit'
  pod 'Alamofire', '~> 5.2.2'
  pod 'AlamofireImage', '~> 4.1.0'
  pod 'FirebaseFirestore'
  pod 'Codextended'
  pod 'Kingfisher'
  pod 'SDWebImage'
  pod 'AYPopupPickerView'
  pod 'YPImagePicker'
  pod "NextLevelSessionExporter"
  pod 'KAPinField'
  pod 'FSPagerView'
  pod 'AKNumericFormatter'
  pod 'Stripe'
  pod 'ContextMenuSwift'
  pod 'SBDropDown'
  pod 'SwiftMessages', '~> 9.0.5'
  pod 'Cosmos', '~> 23.0'
  pod 'SKPhotoBrowser'
  pod 'MaterialComponents'
  pod 'MDFInternationalization'
  pod 'PopupDialog'
  pod 'Toast-Swift', '~> 4.0.1'
  pod 'SVProgressHUD'
  pod 'DropDown'
  pod 'GooglePlaces'
  pod 'SwiftPullToRefresh'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
         end
    end
  end
end



